services:
  db:
    image: postgres:15
    container_name: bankcards-postgres
    environment:
      POSTGRES_DB: bankcards
      POSTGRES_USER: bankcards
      POSTGRES_PASSWORD: bankcards
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  app:
    build: .
    container_name: bankcards-app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bankcards
      SPRING_DATASOURCE_USERNAME: bankcards
      SPRING_DATASOURCE_PASSWORD: bankcards
    ports:
      - "8080:8080"

volumes:
  postgres: